# Generated by Django 4.0.5 on 2022-06-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_group'),
        ('groups', '0001_initial'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='animals',
            field=models.ManyToManyField(related_name='animals', to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='groups.group'),
        ),
    ]
