# Generated by Django 4.0.5 on 2022-06-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_characteristic_animals_alter_characteristic_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='groups',
        ),
    ]
