# Generated by Django 4.0.5 on 2022-06-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_remove_characteristic_animals_and_more'),
        ('groups', '0001_initial'),
        ('animals', '0002_alter_animal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristic',
            field=models.ManyToManyField(related_name='animals', to='characteristics.characteristic'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='groups.group'),
        ),
    ]
