# Generated by Django 4.0.5 on 2022-06-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_characteristic_alter_animal_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='characteristic',
            new_name='characteristics',
        ),
    ]
